apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: master
        image: gefb2000/demucs-worker:latest
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: FLASK_HOST
          value: "0.0.0.0"
        - name: FLASK_PORT
          value: "5000"
        - name: MINIO_HOST
          value: "minio-proj.minio-ns.svc.cluster.local:9000"
---