apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  ports:
  - protocol: "TCP"
    port: 5000  # port that worker service listens on
    targetPort: 5000  # port that worker service listens on
  selector:
    app: worker
